### ISSUE TITLE
redmine: Markdownテキスト中のURLリンクが消失する

### ISSUE THREAD

**Issue by fujimotos** [clear-code/statistics#100]
Markdown形式のコメント欄に http://.../ のリンクを張った場合に再現。
HTML変換の過程でURLが滅失する事がある。

### 再現方法

Markdownを有効にしたredmineで、次の内容をコメントとして投稿する：

```
http://google.com/
http://google.com/あいうえお
```

すると2行目のリンクが消えてしまうことが確認できる：

![2017-12-28-132502_286x86_scrot](https://user-images.githubusercontent.com/8974561/34400232-95a1c808-ebd2-11e7-829a-8edb97ff722b.png)

**Comment by ashie** [comment]
以下を使っているサイトで発生している問題

https://github.com/okkez/redmine_common_mark

**Comment by ashie** [comment]
> http://google.com/
> http://google.com/あいうえお

再現させてみたところ、1行目は関係なくて、2行目だけでも発生する
また、「あhttp://google.com/い」とすると、「あ」だけが表示される。

**Comment by ashie** [comment]
デバッグ環境のセットアップ

```sh
$ git clone https://github.com/redmine/redmine.git
$ cd plugins
$ git clone https://github.com/okkez/redmine_common_mark.git common_mark
$ cd ..
$ bundle install --path vendor/bundle
$ vi config/database.yml
$ rake db:setup
$ rake db:migrate
$ cd config
$ cp configuration.yml.example configuration.yml.example
$ rake secret
$ vi configuretion.yml (secret_tokenに上記の出力をセット)
$ cd ..
```

config/database.yml:
```yml
production:
  adapter: sqlite3
  database: db/redmine-production.sqlite3

development:
  adapter: sqlite3
  database: db/redmine.sqlite3

test:
  adapter: sqlite3
  database: db/redmine-test.sqlite3
```

テストの走らせ方
```sh
$ rake redmine:plugins:test:units
```

再現方法

* Redmineを上げる
```
$ ./bin/rails s
$ firefox http://localhost:3000
```
* admin:adminでログイン
* 「管理」→「設定」
* 「テキスト書式」を「CommonMark」に
* 適当なプロジェクトを作って現象を再現させる
